In [1]:
import numpy

In [2]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

In [5]:
type(m)

numpy.ndarray

In [6]:
#pip install opencv-python

In [7]:
import cv2

In [8]:
im_g=cv2.imread("smallgray.png",2)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
cv2.imwrite("smallgray.png",im_g)

True

In [10]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [11]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [12]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [13]:
ims=numpy.hstack((im_g,im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [14]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [15]:
ims=numpy.vstack(im_g)

In [16]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [17]:
lst=numpy.hsplit(ims,5)

In [18]:
print(lst)

[array([[187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182]], dtype=uint8)]
